# Generated by Django 4.1.7 on 2023-04-03 14:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAdvt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_documents_checked', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_new_advts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('square_feet', models.FloatField(null=True)),
                ('number_of_rooms', models.CharField(max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('floors_at_house', models.IntegerField(default=1)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('parking', models.CharField(choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], default='Нет', max_length=20)),
                ('balcony', models.BooleanField(default=False, null=True)),
                ('loggia', models.BooleanField(default=False, null=True)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('dishwasher', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('water_heater', models.BooleanField(default=False)),
                ('stove', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('microwave', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('iron', models.BooleanField(default=False)),
                ('wi_fi', models.BooleanField(default=False)),
                ('cabel_TV', models.BooleanField(default=False)),
                ('bed_sheets', models.BooleanField(default=False)),
                ('towels', models.BooleanField(default=False)),
                ('hygiene_products', models.BooleanField(default=False)),
                ('max_people', models.CharField(max_length=20)),
                ('childs', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('events', models.BooleanField(default=False)),
                ('accounting_documents', models.BooleanField(default=False)),
                ('monthly_rent', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rep_photo', models.FileField(blank=True, upload_to='room_images')),
                ('room_type', models.CharField(choices=[('Private room', 'PRIVATE ROOM'), ('Shared room', 'SHARED ROOM'), ('Entire home/apt', 'ENTIRE HOUSE')], default='Entire home/apt', max_length=20)),
                ('secondary_id', models.IntegerField()),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteAdvt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_user_favorites', to='rental.newadvt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_id_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_search', to=settings.AUTH_USER_MODEL)),
                ('room_id_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_search', to='rental.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('secondary_id', models.IntegerField()),
                ('renter_id_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_rate', to=settings.AUTH_USER_MODEL)),
                ('room_id_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rate', to='rental.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='user_images')),
                ('room_id_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_img', to='rental.room')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_id_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_recom', to=settings.AUTH_USER_MODEL)),
                ('room_id_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_recom', to='rental.room')),
            ],
        ),
        migrations.CreateModel(
            name='NewAdvtLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('advt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_advt_location', to='rental.newadvt')),
            ],
        ),
        migrations.CreateModel(
            name='NewAdvtLastStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('video', models.URLField(blank=True, null=True)),
                ('rep_photo', models.FileField(blank=True, upload_to='new_advt_main_images')),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('advt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_advt_last_step', to='rental.newadvt')),
            ],
        ),
        migrations.CreateModel(
            name='NewAdvtInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=1)),
                ('floors_at_house', models.IntegerField(default=1)),
                ('parking', models.CharField(choices=[('Нет', 'Нет'), ('На улице', 'На улице'), ('В здании', 'В здании')], default='Нет', max_length=20)),
                ('square_feet', models.FloatField()),
                ('number_of_rooms', models.CharField(max_length=20)),
                ('balcony', models.BooleanField(default=False)),
                ('loggia', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('dishwasher', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('water_heater', models.BooleanField(default=False)),
                ('stove', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('microwave', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('iron', models.BooleanField(default=False)),
                ('wi_fi', models.BooleanField(default=False)),
                ('cabel_TV', models.BooleanField(default=False)),
                ('bed_sheets', models.BooleanField(default=False)),
                ('towels', models.BooleanField(default=False)),
                ('hygiene_products', models.BooleanField(default=False)),
                ('max_people', models.CharField(max_length=20)),
                ('childs', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('events', models.BooleanField(default=False)),
                ('accounting_documents', models.BooleanField(default=False)),
                ('monthly_rent', models.BooleanField(default=False)),
                ('advt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_advt_information', to='rental.newadvt')),
            ],
        ),
        migrations.CreateModel(
            name='NewAdvtImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='new_advt_addition_images')),
                ('advt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_advt_images', to='rental.newadvt')),
            ],
        ),
        migrations.CreateModel(
            name='HostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('host_id_hostRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_hostRate', to=settings.AUTH_USER_MODEL)),
                ('renter_id_hostRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_hostRate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsCheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents_check_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_id_click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_click', to=settings.AUTH_USER_MODEL)),
                ('room_id_click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_click', to='rental.room')),
            ],
        ),
        migrations.CreateModel(
            name='AdvtReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Принят', 'Принят'), ('Отклонён', 'Отклонён'), ('Отменён', 'Отменён'), ('Завершён', 'Завершён')], default='На рассмотрении', max_length=30)),
                ('advt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rental.newadvt')),
                ('renter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
