# Generated by Django 4.1.7 on 2023-03-27 23:35

import apps.chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('t', 'Text'), ('i', 'Image')], default='t', max_length=1)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(blank=True, max_length=2200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.chat.models.MessageFeatures.create_temp_path)),
                ('seen', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message Features',
                'verbose_name_plural': 'Message Features',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(blank=True, related_name='whos', to='chat.messagefeatures')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
