# Generated by Django 4.1.7 on 2023-03-28 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(blank=True, related_name='chat_messages', to='chat.messages')),
                ('participants', models.ManyToManyField(related_name='user_dialogues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
