# Generated by Django 4.1.7 on 2023-03-28 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
